In [92]:
import pandas
import numpy as np


dTrain = pandas.read_csv('TrainsetTugas1ML.csv').as_matrix().tolist()
dFrame = pandas.DataFrame(dTrain)
dFrame

0      1                 2             3                   4  \
0     4776  young           Private  Some-college  Married-civ-spouse   
1     8173  adult           Private     Bachelors       Never-married   
2    23423  young           Private  Some-college  Married-civ-spouse   
3     1818  adult           Private       HS-grad  Married-civ-spouse   
4    14894  adult           Private     Bachelors            Divorced   
5    13128  adult         Local-gov     Bachelors  Married-civ-spouse   
6    29619  adult           Private  Some-college  Married-civ-spouse   
7     2308  adult           Private     Bachelors  Married-civ-spouse   
8     9606  adult  Self-emp-not-inc  Some-college            Divorced   
9    15394  adult           Private     Bachelors  Married-civ-spouse   
10   14741  young           Private       HS-grad  Married-civ-spouse   
11   21019  adult         Local-gov       HS-grad  Married-civ-spouse   
12    9847  young  Self-emp-not-inc  Some-college  Married-civ-spouse   
13   12546  young           Private     Bachelors  Married-civ-spouse   
14    8930  adult           Private       HS-grad            Divorced   
15    2603  young           Private       HS-grad            Divorced   
16   16168  young           Private     Bachelors       Never-married   
17   16165  adult           Private       HS-grad  Married-civ-spouse   
18   26180  adult           Private  Some-college  Married-civ-spouse   
19    8209  young           Private     Bachelors  Married-civ-spouse   
20   14147  young           Private     Bachelors  Married-civ-spouse   
21   10512  young           Private       HS-grad  Married-civ-spouse   
22   21375  young           Private     Bachelors  Married-civ-spouse   
23   23562  adult           Private     Bachelors  Married-civ-spouse   
24   19154  young           Private     Bachelors  Married-civ-spouse   
25   11091  adult           Private  Some-college  Married-civ-spouse   
26   12232  young           Private  Some-college  Married-civ-spouse   
27   19725  young  Self-emp-not-inc     Bachelors  Married-civ-spouse   
28   24980  young           Private  Some-college  Married-civ-spouse   
29    7834  young           Private       HS-grad            Divorced   
..     ...    ...               ...           ...                 ...   
130   8195  young           Private     Bachelors  Married-civ-spouse   
131  18210  young           Private  Some-college  Married-civ-spouse   
132   5748  young           Private  Some-college  Married-civ-spouse   
133  20883  young           Private  Some-college       Never-married   
134  28940  adult           Private     Bachelors  Married-civ-spouse   
135  32117  adult           Private       HS-grad  Married-civ-spouse   
136   9639  adult           Private     Bachelors  Married-civ-spouse   
137  23052    old           Private     Bachelors  Married-civ-spouse   
138  12503  young           Private       HS-grad  Married-civ-spouse   
139  29275  young           Private     Bachelors  Married-civ-spouse   
140  20928  adult           Private  Some-college  Married-civ-spouse   
141  16832  adult           Private     Bachelors  Married-civ-spouse   
142  15777  adult           Private       HS-grad  Married-civ-spouse   
143  10409  young           Private     Bachelors  Married-civ-spouse   
144   5470  young  Self-emp-not-inc       HS-grad            Divorced   
145  28990  young  Self-emp-not-inc  Some-college  Married-civ-spouse   
146   3348  young           Private       HS-grad  Married-civ-spouse   
147  27044  young           Private     Bachelors  Married-civ-spouse   
148  14364  young           Private  Some-college       Never-married   
149  32484  adult           Private  Some-college            Divorced   
150   8910  young           Private     Bachelors  Married-civ-spouse   
151  14676  adult           Private       HS-grad  Married-civ-spouse   
152  25586  young           Private  Some-college  Married-civ-spou

In [93]:
dkeList = dFrame[1].tolist()
set(dkeList)

{'adult', 'old', 'young'}

In [94]:
#mengetahui isi label per setiap atribut dimana setiap atribut memiliki 3 label
label = []
for i in range (1,9):
    dkeList = dFrame[i].tolist()
    label.append(list(set(dkeList)))
label

[['old', 'adult', 'young'],
 ['Self-emp-not-inc', 'Local-gov', 'Private'],
 ['HS-grad', 'Some-college', 'Bachelors'],
 ['Married-civ-spouse', 'Never-married', 'Divorced'],
 ['Exec-managerial', 'Craft-repair', 'Prof-specialty'],
 ['Husband', 'Not-in-family', 'Own-child'],
 ['normal', 'many', 'low'],
 ['<=50K', '>50K']]

In [95]:
print (label[0][0])
#mengubah nilai yang berada pada setiap isi indeksn tersebut dengan angka 0,1,2
for i in range(len(label)-1):
    for j in range(3):
        #mengubah nilai yang berada pada setiap isi indeksn tersebut dengan angka 0,1,2
        dFrame = dFrame.replace({label[i][j]: j})
#untuk kategori income diganti dengan angka 0 dan 1 
dFrame = dFrame.replace({'>50K' : 0, '<=50K' :1})
dFrame

old


0  1  2  3  4  5  6  7  8
0     4776  2  2  1  0  2  0  0  0
1     8173  1  2  2  1  2  1  0  0
2    23423  2  2  1  0  2  0  0  0
3     1818  1  2  0  0  1  0  0  1
4    14894  1  2  2  2  0  1  0  0
5    13128  1  1  2  0  2  0  0  0
6    29619  1  2  1  0  2  0  0  0
7     2308  1  2  2  0  2  0  0  0
8     9606  1  0  1  2  1  1  0  1
9    15394  1  2  2  0  0  0  0  0
10   14741  2  2  0  0  0  0  0  0
11   21019  1  1  0  0  1  0  0  0
12    9847  2  0  1  0  1  0  0  0
13   12546  2  2  2  0  0  0  0  0
14    8930  1  2  0  2  1  1  0  1
15    2603  2  2  0  2  0  1  0  0
16   16168  2  2  2  1  2  1  0  0
17   16165  1  2  0  0  0  0  0  0
18   26180  1  2  1  0  2  0  0  0
19    8209  2  2  2  0  0  0  0  0
20   14147  2  2  2  0  0  0  0  0
21   10512  2  2  0  0  1  0  0  0
22   21375  2  2  2  0  2  0  0  0
23   23562  1  2  2  0  0  0  0  0
24   19154  2  2  2  0  2  0  0  0
25   11091  1  2  1  0  2  0  0  0
26   12232  2  2  1  0  0  0  0  0
27   19725  2  0  2  0  2  0  0  0
28   24980  2  2  1  0  1  0  0  1
29    7834  2  2  0  2  1  1  0  0
..     ... .. .. .. .. .. .. .. ..
130   8195  2  2  2  0  2  0  0  0
131  18210  2  2  1  0  1  0  0  0
132   5748  2  2  1  0  0  0  0  0
133  20883  2  2  1  1  2  2  0  1
134  28940  1  2  2  0  2  0  0  0
135  32117  1  2  0  0  1  0  0  0
136   9639  1  2  2  0  0  0  0  0
137  23052  0  2  2  0  0  0  0  0
138  12503  2  2  0  0  1  0  0  0
139  29275  2  2  2  0  0  0  0  1
140  20928  1  2  1  0  0  0  0  0
141  16832  1  2  2  0  0  0  0  0
142  15777  1  2  0  0  1  0  1  0
143  10409  2  2  2  0  0  0  0  0
144   5470  2  0  0  2  1  1  0  1
145  28990  2  0  1  0  0  0  0  1
146   3348  2  2  0  0  1  0  0  1
147  27044  2  2  2  0  1  0  0  0
148  14364  2  2  1  1  1  1  0  1
149  32484  1  2  1  2  0  1  0  1
150   8910  2  2  2  0  2  0  0  0
151  14676  1  2  0  0  0  0  0  0
152  25586  2  2  1  0  1  0  0  0
153  23955  2  2  0  0  1  0  0  0
154  11007  1  2  1  0  0  0  0  0
155  26037  2  2  0  0  2  0  0  0
156  12777  1  2  1  2  1  1  0  1
157  11461  1  2  1  0  1  0  0  1
158  31461  1  2  0  0  1  0  0  0
159  23157  0  1  0  0  0  0  2  1

[160 rows x 9 columns]

In [96]:
# dFrame

In [97]:
#kita akan membuat table yang akan menghasilkan yang berdasarkan 7 atribut dan masing masing sesuai umur dan memiliki target
adFrame = np.asarray(dFrame)

print(len(adFrame))

160


In [98]:
#membuat array baru dengan dimensi 7x3x2
arrayKosong = np.zeros((7,3,2))

In [99]:
for e in (adFrame): #jadi variable e mengeluarkan value dari indeks 
    for i in range(1,len(e)-1):
        arrayKosong[i-1][e[i]][e[8]] += 1
arrayKosong

array([[[  1.,   1.],
        [ 53.,  19.],
        [ 66.,  20.]],

       [[  7.,   7.],
        [  8.,   1.],
        [105.,  32.]],

       [[ 28.,  17.],
        [ 27.,  16.],
        [ 65.,   7.]],

       [[108.,  19.],
        [  7.,  14.],
        [  5.,   7.]],

       [[ 47.,  15.],
        [ 32.,  21.],
        [ 41.,   4.]],

       [[107.,  19.],
        [ 11.,  14.],
        [  2.,   7.]],

       [[116.,  33.],
        [  1.,   2.],
        [  3.,   5.]]])

In [109]:
#membuat array dengan dimensi 7x4x3 untuk nilai pembanding
arrayBaru = np.zeros((7,4,2))
for e in range(len(arrayKosong)):
    pembanding = np.sum(arrayKosong[e], axis = 0)
    arrayBaru[e][3] = pembanding
arrayBaru

array([[[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.],
        [120.,  40.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.],
        [120.,  40.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.],
        [120.,  40.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.],
        [120.,  40.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.],
        [120.,  40.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.],
        [120.,  40.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.],
        [120.,  40.]]])

In [110]:
#membuka file test set dengan mengubahnya ke dalam list
dTest = pandas.read_csv('TestsetTugas1ML.csv').as_matrix().tolist()
dFrameTest = pandas.DataFrame(dTest)
dFrameTest

0      1                 2             3                   4  \
0   26027  young           Private       HS-grad       Never-married   
1   26314  young           Private     Bachelors            Divorced   
2   31405  young           Private     Bachelors  Married-civ-spouse   
3   14736  adult           Private  Some-college            Divorced   
4   27217  young           Private       HS-grad  Married-civ-spouse   
5    5951  young           Private     Bachelors       Never-married   
6   30067  young         Local-gov     Bachelors       Never-married   
7   28777  young  Self-emp-not-inc  Some-college       Never-married   
8   15390  adult           Private  Some-college  Married-civ-spouse   
9   18042  young           Private  Some-college  Married-civ-spouse   
10   5793  adult         Local-gov       HS-grad  Married-civ-spouse   
11  31274  adult           Private       HS-grad  Married-civ-spouse   
12  17068  young           Private       HS-grad  Married-civ-spouse   
13  21894  young           Private     Bachelors  Married-civ-spouse   
14  24128  adult           Private     Bachelors  Married-civ-spouse   
15   8550  young           Private     Bachelors  Married-civ-spouse   
16   1181  young           Private     Bachelors            Divorced   
17  11149  adult           Private       HS-grad  Married-civ-spouse   
18  20836  young           Private  Some-college       Never-married   
19  25766  adult         Local-gov     Bachelors  Married-civ-spouse   
20    139  adult           Private  Some-college  Married-civ-spouse   
21  27160  young           Private     Bachelors  Married-civ-spouse   
22   8814  young           Private       HS-grad  Married-civ-spouse   
23  11470  young           Private     Bachelors  Married-civ-spouse   
24  16694  adult           Private       HS-grad  Married-civ-spouse   
25  26906  adult           Private     Bachelors  Married-civ-spouse   
26   9890  adult           Private  Some-college  Married-civ-spouse   
27   9769  adult           Private     Bachelors  Married-civ-spouse   
28  11078  adult           Private     Bachelors  Married-civ-spouse   
29  12924  young           Private     Bachelors       Never-married   
30  26020  adult           Private       HS-grad       Never-married   
31   9017  young           Private  Some-college            Divorced   
32  10243  adult  Self-emp-not-inc  Some-college  Married-civ-spouse   
33  10882  young           Private       HS-grad  Married-civ-spouse   
34  19535  young  Self-emp-not-inc       HS-grad       Never-married   
35   4565  adult           Private     Bachelors  Married-civ-spouse   
36  29102  young           Private  Some-college       Never-married   
37  26673  adult           Private       HS-grad  Married-civ-spouse   
38  29415  adult           Private       HS-grad  Married-civ-spouse   
39  17397  adult           Private  Some-college  Married-civ-spouse   

                  5              6       7  
0      Craft-repair  Not-in-family  normal  
1   Exec-managerial  Not-in-family  normal  
2    Prof-specialty        Husband  normal  
3    Prof-specialty  Not-in-family  normal  
4   Exec-managerial        Husband    many  
5    Prof-specialty  Not-in-family  normal  
6      Craft-repair  Not-in-family  normal  
7      Craft-repair  Not-in-family  normal  
8      Craft-repair        Husband  normal  
9   Exec-managerial        Husband  normal  
10  Exec-managerial        Husband  normal  
11     Craft-repair        Husband  normal  
12     Craft-repair        Husband     low  
13   Prof-specialty        Husband  normal  
14  Exec-managerial        Husband  normal  
15   Prof-specialty        Husband  normal  
16  Exec-managerial  Not-in-family  normal  
17     Craft-repair        Husband  normal  
18   Prof-specialty  Not-in-family  normal  
19   Prof-specialty        Husband  normal  
20     Craft-repair        Husband  normal  
21  Exec-managerial        Husband  normal  
22  Exec-managerial 

In [111]:
#mengetahui isi label per setiap atribut dimana setiap atribut memiliki 3 label
label_test = []
for i in range (1,8):
    ubahTestKeList = dFrameTest[i].tolist()
    label_test.append(list(set(ubahTestKeList)))
label_test

[['adult', 'young'],
 ['Self-emp-not-inc', 'Local-gov', 'Private'],
 ['HS-grad', 'Some-college', 'Bachelors'],
 ['Divorced', 'Never-married', 'Married-civ-spouse'],
 ['Exec-managerial', 'Craft-repair', 'Prof-specialty'],
 ['Husband', 'Not-in-family'],
 ['normal', 'many', 'low']]

In [112]:
for i in range(len(label)-1):
    for j in range(3):
        dFrameTest = dFrameTest.replace({label[i][j]: j}) 

In [113]:
#mengubah nilai yang berada pada setiap isi indeksn tersebut dengan angka 0,1,2
dFrameTest
        
# dFrameTest = dFrameTest.replace({'>50K' : 0, '<=50K' :1})
dFT = np.asarray(dFrameTest)
dFT

array([[26027,     2,     2,     0,     1,     1,     1,     0],
       [26314,     2,     2,     2,     2,     0,     1,     0],
       [31405,     2,     2,     2,     0,     2,     0,     0],
       [14736,     1,     2,     1,     2,     2,     1,     0],
       [27217,     2,     2,     0,     0,     0,     0,     1],
       [ 5951,     2,     2,     2,     1,     2,     1,     0],
       [30067,     2,     1,     2,     1,     1,     1,     0],
       [28777,     2,     0,     1,     1,     1,     1,     0],
       [15390,     1,     2,     1,     0,     1,     0,     0],
       [18042,     2,     2,     1,     0,     0,     0,     0],
       [ 5793,     1,     1,     0,     0,     0,     0,     0],
       [31274,     1,     2,     0,     0,     1,     0,     0],
       [17068,     2,     2,     0,     0,     1,     0,     2],
       [21894,     2,     2,     2,     0,     2,     0,     0],
       [24128,     1,     2,     2,     0,     0,     0,     0],
       [ 8550,     2,    

In [114]:
#Naive Bayes
#membuat array baru dengan dengan ukuran yang sesuai dengan banyaknya 40 (meneyesuaikan dengan isi dalam data testset) indeks yang menyimpan hasil data set yang akan diberikan label
array_total = np.ones((40,2))
variable_iterasi = 0

for i in range(len(dFT)):
    for j in range(1, 8):
        variable_0 = arrayKosong[j-1][dFT[i][j]][0]/arrayBaru[j-1][3][0] #kelas 0, menyimpan label kelas 0 
        variable_1 = arrayKosong[j-1][dFT[i][j]][1]/arrayBaru[j-1][3][1] #kelas 1, menyimpan label kelas 1
        array_total[variable_iterasi][0]*= variable_0  #mengalikan ke dalam array_total sacara keseluruhan dengan variable 0
        array_total[variable_iterasi][1]*= variable_1 #mengalikan ke dalam array_total sacara keseluruhan dengan variable 0
    array_total[variable_iterasi][0]*= 120/160 #variable 0 memiliki totak yakni <=50K jadi akan dihitung probabilitasnya dengan keseluruhan banyaknya <=50k dengan pembandingnya jumlah keseluruhan label kelas
    array_total[variable_iterasi][1]*= 40/160 #variable 1 memiliki totak yakni >50K jadi akan dihitung probabilitasnya dengan keseluruhan banyaknya >50k dengan pembandingnya jumlah keseluruhan label kelas
    variable_iterasi += 1
    
    
print(array_total)

[[1.16086709e-04 2.25495703e-03]
 [2.82720740e-04 3.31611328e-04]
 [5.18189384e-02 3.25746094e-04]
 [8.22670661e-05 1.92018750e-04]
 [2.20591715e-04 1.79794922e-04]
 [3.45280223e-04 1.76859375e-04]
 [2.05323431e-05 2.90159912e-05]
 [7.46271701e-06 4.64255859e-04]
 [1.34907773e-02 3.71350547e-03]
 [2.46747590e-02 2.79210937e-03]
 [1.56559638e-03 8.80714188e-05]
 [1.39904358e-02 3.94559956e-03]
 [4.50570313e-04 6.29282227e-04]
 [5.18189384e-02 3.25746094e-04]
 [4.77017648e-02 1.16047046e-03]
 [5.18189384e-02 3.25746094e-04]
 [2.82720740e-04 3.31611328e-04]
 [1.39904358e-02 3.94559956e-03]
 [1.43424093e-04 4.04250000e-04]
 [3.17045164e-03 9.67058716e-06]
 [1.34907773e-02 3.71350547e-03]
 [5.94021977e-02 1.22154785e-03]
 [2.55886390e-02 2.96661621e-03]
 [5.94021977e-02 1.22154785e-03]
 [1.39904358e-02 3.94559956e-03]
 [3.24777973e-02 1.62465864e-03]
 [1.34907773e-02 3.71350547e-03]
 [4.16121778e-02 3.09458789e-04]
 [4.77017648e-02 1.16047046e-03]
 [2.32316382e-06 5.62734375e-05]
 [9.322114

In [115]:
# mengetahui nilai maksimum tapi keluarannya yakni indeks yang memiliki nilai terbesar
a = np.argmax(array_total, axis=1)

In [116]:
hasil = pandas.DataFrame(a).replace({0: '>50K', 1: '<=50K'})

hasil

0
0   <=50K
1   <=50K
2    >50K
3   <=50K
4    >50K
5    >50K
6   <=50K
7   <=50K
8    >50K
9    >50K
10   >50K
11   >50K
12  <=50K
13   >50K
14   >50K
15   >50K
16  <=50K
17   >50K
18  <=50K
19   >50K
20   >50K
21   >50K
22   >50K
23   >50K
24   >50K
25   >50K
26   >50K
27   >50K
28   >50K
29  <=50K
30  <=50K
31  <=50K
32   >50K
33   >50K
34  <=50K
35   >50K
36  <=50K
37   >50K
38   >50K
39   >50K

In [117]:
hasil.to_csv('TebakanTugas1ML.csv.csv', header=False, index=False)